version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+asyncmy://user:password@db/ecommerce
      - JWT_SECRET=your-secure-jwt-secret-key
    volumes:
      - .:/app
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api
volumes:
  db-data: